name: im_mottu_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Icons
  cupertino_icons: ^1.0.2

  #Network-requests
  dio: 5.1.1

  #Cryptographic hashing functions for Dart.
  crypto: 3.0.3

  #Responsible for the dependency injection system and route management
  flutter_modular: 5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
