name: im_mottu_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Icons
  cupertino_icons: ^1.0.2

  #Network-requests
  dio: 5.1.1

  #Cryptographic hashing functions for Dart.
  crypto: 3.0.3

  #Responsible for the dependency injection system and route management
  flutter_modular: 5.0.3

  #Firebase
  firebase_core: 2.11.0
  firebase_crashlytics: 3.2.0
  firebase_remote_config: 4.1.0
  firebase_analytics: 10.3.0

  #Store data in key-value format
  shared_preferences: 2.1.0

  #manager state
  get: 4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

