// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx9AkQGY8LJlK_XmlrdR5Flnw0KTjONWk',
    appId: '1:530924307633:web:e16144e38b76e30dc94e90',
    messagingSenderId: '530924307633',
    projectId: 'im-mottu-mobile',
    authDomain: 'im-mottu-mobile.firebaseapp.com',
    storageBucket: 'im-mottu-mobile.appspot.com',
    measurementId: 'G-YX1Z9ZQ6TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz2oaD_4xmXnpay063jDB94bD4ZCrNojg',
    appId: '1:530924307633:android:4707e62ea3fe578ec94e90',
    messagingSenderId: '530924307633',
    projectId: 'im-mottu-mobile',
    storageBucket: 'im-mottu-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm787LvCTaWdFYCHh0D2wrjBdGvkuZKlo',
    appId: '1:530924307633:ios:6b22d265b866d87fc94e90',
    messagingSenderId: '530924307633',
    projectId: 'im-mottu-mobile',
    storageBucket: 'im-mottu-mobile.appspot.com',
    iosClientId: '530924307633-fupc48tmv68rpmrq5vfv3e02s2nasni8.apps.googleusercontent.com',
    iosBundleId: 'com.mottu.marvel.imMottuMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm787LvCTaWdFYCHh0D2wrjBdGvkuZKlo',
    appId: '1:530924307633:ios:6b22d265b866d87fc94e90',
    messagingSenderId: '530924307633',
    projectId: 'im-mottu-mobile',
    storageBucket: 'im-mottu-mobile.appspot.com',
    iosClientId: '530924307633-fupc48tmv68rpmrq5vfv3e02s2nasni8.apps.googleusercontent.com',
    iosBundleId: 'com.mottu.marvel.imMottuMobile',
  );
}
